"""Initial migration

Revision ID: 9d9d627b8dbb
Revises: 5ec931d02924
Create Date: 2025-08-10 06:00:22.456942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9d627b8dbb'
down_revision = '5ec931d02924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user_email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('assigned_user_email')

    # ### end Alembic commands ###
